//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_ErrorLogs
    {
        public int ErrorLogID { get; set; }
        public bool IsHandled { get; set; }
        public string ResourceUri { get; set; }
        public string QueryString { get; set; }
        public System.DateTime ErrorDatetimeUtc { get; set; }
        public string ErrorMessage { get; set; }
        public string ExceptionDetail { get; set; }
        public string StackTrace { get; set; }
        public string IpAddress { get; set; }
        public string UserID { get; set; }
        public string ReferingUrl { get; set; }
        public string UserAgent { get; set; }
    }
}
