//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_UserDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegaSys_UserDetail()
        {
            this.LegaSys_Attachments = new HashSet<LegaSys_Attachments>();
            this.LegaSys_Attachments1 = new HashSet<LegaSys_Attachments>();
            this.LegaSys_ClientDetails = new HashSet<LegaSys_ClientDetails>();
            this.LegaSys_ClientDetails1 = new HashSet<LegaSys_ClientDetails>();
            this.LegaSys_Menu_Roles = new HashSet<LegaSys_Menu_Roles>();
            this.LegaSys_Menu_Roles1 = new HashSet<LegaSys_Menu_Roles>();
            this.LegaSys_ProjectResource = new HashSet<LegaSys_ProjectResource>();
            this.LegaSys_ProjectResource1 = new HashSet<LegaSys_ProjectResource>();
            this.LegaSys_ProjectResource2 = new HashSet<LegaSys_ProjectResource>();
            this.LegaSys_Projects = new HashSet<LegaSys_Projects>();
            this.LegaSys_Projects1 = new HashSet<LegaSys_Projects>();
            this.LegaSys_ProjectSubTasks = new HashSet<LegaSys_ProjectSubTasks>();
            this.LegaSys_ProjectSubTasks1 = new HashSet<LegaSys_ProjectSubTasks>();
            this.LegaSys_ProjectTasks = new HashSet<LegaSys_ProjectTasks>();
            this.LegaSys_ProjectTasks1 = new HashSet<LegaSys_ProjectTasks>();
            this.LegaSys_ProjectTechDetail = new HashSet<LegaSys_ProjectTechDetail>();
            this.LegaSys_ProjectTechDetail1 = new HashSet<LegaSys_ProjectTechDetail>();
            this.LegaSys_UserDetail1 = new HashSet<LegaSys_UserDetail>();
            this.LegaSys_UserTechDetail = new HashSet<LegaSys_UserTechDetail>();
            this.LegaSys_UserDetail11 = new HashSet<LegaSys_UserDetail>();
            this.LegaSys_UserTechDetail1 = new HashSet<LegaSys_UserTechDetail>();
            this.LegaSys_UserDetail12 = new HashSet<LegaSys_UserDetail>();
            this.LegaSys_UserTechDetail2 = new HashSet<LegaSys_UserTechDetail>();
            this.LegaSys_UserLoginDetails = new HashSet<LegaSys_UserLoginDetails>();
            this.LegaSys_UserLoginDetails1 = new HashSet<LegaSys_UserLoginDetails>();
            this.LegaSys_UserLoginDetails2 = new HashSet<LegaSys_UserLoginDetails>();
        }
    
        public int UserDetailID { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public Nullable<decimal> TotalExp { get; set; }
        public string EmailId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Master_Shift_ID { get; set; }
        public Nullable<int> Master_Location_ID { get; set; }
        public Nullable<int> ReportingHead_ID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public Nullable<int> Master_UserRoles_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_Attachments> LegaSys_Attachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_Attachments> LegaSys_Attachments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ClientDetails> LegaSys_ClientDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ClientDetails> LegaSys_ClientDetails1 { get; set; }
        public virtual LegaSys_Master_Locations LegaSys_Master_Locations { get; set; }
        public virtual LegaSys_Master_Shifts LegaSys_Master_Shifts { get; set; }
        public virtual LegaSys_Master_UserRoles LegaSys_Master_UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_Menu_Roles> LegaSys_Menu_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_Menu_Roles> LegaSys_Menu_Roles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectResource> LegaSys_ProjectResource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectResource> LegaSys_ProjectResource1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectResource> LegaSys_ProjectResource2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_Projects> LegaSys_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_Projects> LegaSys_Projects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectSubTasks> LegaSys_ProjectSubTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectSubTasks> LegaSys_ProjectSubTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectTasks> LegaSys_ProjectTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectTasks> LegaSys_ProjectTasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectTechDetail> LegaSys_ProjectTechDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectTechDetail> LegaSys_ProjectTechDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserDetail> LegaSys_UserDetail1 { get; set; }
        public virtual LegaSys_UserDetail LegaSys_UserDetail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserTechDetail> LegaSys_UserTechDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserDetail> LegaSys_UserDetail11 { get; set; }
        public virtual LegaSys_UserDetail LegaSys_UserDetail3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserTechDetail> LegaSys_UserTechDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserDetail> LegaSys_UserDetail12 { get; set; }
        public virtual LegaSys_UserDetail LegaSys_UserDetail4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserTechDetail> LegaSys_UserTechDetail2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserLoginDetails> LegaSys_UserLoginDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserLoginDetails> LegaSys_UserLoginDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserLoginDetails> LegaSys_UserLoginDetails2 { get; set; }
    }
}
