//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_Log_Projects
    {
        public int LogID { get; set; }
        public int RecordID { get; set; }
        public string TableName { get; set; }
        public string FieldDescription { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime EntryDateTime { get; set; }
        public int UserResponsible { get; set; }
    
        public virtual LegaSys_UserDetails LegaSys_UserDetails { get; set; }
    }
}
