//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegaSysEntities : DbContext
    {
        public LegaSysEntities()
            : base("name=LegaSysEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LegaSys_Attachments> LegaSys_Attachments { get; set; }
        public virtual DbSet<LegaSys_AttachmentTypes> LegaSys_AttachmentTypes { get; set; }
        public virtual DbSet<LegaSys_ClientDetails> LegaSys_ClientDetails { get; set; }
        public virtual DbSet<LegaSys_Master_Locations> LegaSys_Master_Locations { get; set; }
        public virtual DbSet<LegaSys_Master_Menu> LegaSys_Master_Menu { get; set; }
        public virtual DbSet<LegaSys_Master_Shifts> LegaSys_Master_Shifts { get; set; }
        public virtual DbSet<LegaSys_Master_TechDomains> LegaSys_Master_TechDomains { get; set; }
        public virtual DbSet<LegaSys_Master_Technology> LegaSys_Master_Technology { get; set; }
        public virtual DbSet<LegaSys_Master_UserRoles> LegaSys_Master_UserRoles { get; set; }
        public virtual DbSet<LegaSys_Menu_Roles> LegaSys_Menu_Roles { get; set; }
        public virtual DbSet<LegaSys_ProjectResource> LegaSys_ProjectResource { get; set; }
        public virtual DbSet<LegaSys_Projects> LegaSys_Projects { get; set; }
        public virtual DbSet<LegaSys_ProjectSubTasks> LegaSys_ProjectSubTasks { get; set; }
        public virtual DbSet<LegaSys_ProjectTasks> LegaSys_ProjectTasks { get; set; }
        public virtual DbSet<LegaSys_ProjectTechDetail> LegaSys_ProjectTechDetail { get; set; }
        public virtual DbSet<LegaSys_UserDetail> LegaSys_UserDetail { get; set; }
        public virtual DbSet<LegaSys_UserLoginDetails> LegaSys_UserLoginDetails { get; set; }
        public virtual DbSet<LegaSys_UserTechDetail> LegaSys_UserTechDetail { get; set; }
    }
}
