//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_RoleMenus
    {
        public int MenuRoleID { get; set; }
        public int Master_Role_ID { get; set; }
        public int Master_Menu_ID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual LegaSys_Master_MenuItems LegaSys_Master_MenuItems { get; set; }
        public virtual LegaSys_Master_Roles LegaSys_Master_Roles { get; set; }
        public virtual LegaSys_UserDetails LegaSys_UserDetails { get; set; }
        public virtual LegaSys_UserDetails LegaSys_UserDetails1 { get; set; }
    }
}
