//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_CoClientDetails
    {
        public int CoClientID { get; set; }
        public int ClientDetailID { get; set; }
        public string CoClientName { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Updated_By { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
        public string phone { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual LegaSys_ClientDetails LegaSys_ClientDetails { get; set; }
    }
}
