//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_UserBackground
    {
        public int BackgroundID { get; set; }
        public int UserDetailID { get; set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public System.DateTime LeavingDate { get; set; }
    }
}
