//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegaSysDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegaSys_Master_Technology
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LegaSys_Master_Technology()
        {
            this.LegaSys_ProjectTechDetail = new HashSet<LegaSys_ProjectTechDetail>();
            this.LegaSys_UserTechDetail = new HashSet<LegaSys_UserTechDetail>();
        }
    
        public int TechnologyID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Master_DomainID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Updated_Date { get; set; }
    
        public virtual LegaSys_Master_TechDomains LegaSys_Master_TechDomains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_ProjectTechDetail> LegaSys_ProjectTechDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegaSys_UserTechDetail> LegaSys_UserTechDetail { get; set; }
    }
}
